- hosts: zabbix-agent
  vars:
    package: zabbix-agent

  tasks:
  - name: Check Zabbix Installed
    shell: dpkg-query -W -f='${Status}' {{ package }} | grep 'install ok installed'
    register: is_installed
    failed_when: no
    changed_when: no

  - name: Remove old Zabbix release repository
    when: is_installed.rc == 0
    apt:
      name: 'zabbix-release'
      state: absent
      purge: yes
      force_apt_get: yes

  - name: Install Zabbix repository for Ubuntu
    when:
    - ansible_distribution == 'Ubuntu'
    - (ansible_distribution_version == '18.04') or (ansible_distribution_version == '16.04') or (ansible_distribution_version == '14.04')
    apt:
      deb: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_distribution_release }}_all.deb


  - name: Install Zabbix repository for Debian
    when: (ansible_distribution == 'Debian') and (ansible_distribution_major_version == '9' or ansible_distribution_major_version == '8')
    apt:
      deb: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_distribution_release }}_all.deb

  - name: Install/upgrade Zabbix Agents
    apt:
      name: '{{ package }}'
      state: latest
      update-cache: yes
      dpkg_options: 'force-confold,force-confdef'
      force_apt_get: yes

  - name: Postinstall configure Zabbix Agents
    replace:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '{{ item.re }}'
      replace: '{{ item.repl }}'
      backup: yes
    loop:
    - {re: '^(Server=).*$', repl: '\1zabbix'}
    - {re: '^(ServerActive=).*$', repl: '\1zabbix'}
    - {re: '^(Hostname=).*$', repl: '\1{{ ansible_fqdn }}'}
    when: is_installed.rc != 0

  - name: Enable and restart Zabbix Agent daemons
    systemd:
      name: '{{ package }}'
      enabled: yes
      masked: no
      state: restarted
      daemon_reload: yes